name: testing-workflow
on: [push]
jobs:
  start-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: node index.js &
      - run: curl http://localhost:3000/
      - run: curl http://localhost:3000/?echop=cryptoxbot
      - run: curl http://localhost:3000/close
